language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '7.3' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
