<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="localhost" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64Binary" targetNamespace="localhost">
  <types>
    <xsd:schema targetNamespace="localhost">
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </xsd:schema>
  </types>
  <portType name="PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryPort">
    <operation name="inputBase64Binary">
      <input message="tns:inputBase64BinaryIn"/>
    </operation>
    <operation name="inputBase64BinaryArray">
      <input message="tns:inputBase64BinaryArrayIn"/>
    </operation>
  </portType>
  <binding name="PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryBinding" type="tns:PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="inputBase64Binary">
      <soap:operation soapAction="localhost#inputBase64Binary"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="localhost"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="localhost"/>
      </output>
    </operation>
    <operation name="inputBase64BinaryArray">
      <soap:operation soapAction="localhost#inputBase64BinaryArray"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="localhost"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="localhost"/>
      </output>
    </operation>
  </binding>
  <message name="inputBase64BinaryIn">
    <part name="base64binary" type="xsd:base64Binary"/>
  </message>
  <message name="inputBase64BinaryArrayIn">
    <part name="base64binaries" type="soap-enc:Array"/>
  </message>
  <service name="PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryService">
    <port name="PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryPort" binding="tns:PHP2WSDL.Test.Fixtures.DataProvider.TestMethodInputBase64BinaryBinding">
      <soap:address location="localhost"/>
    </port>
  </service>
</definitions>
